require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Naming/FileName:
  Exclude:
    - lib/bp3-hello-world.rb

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
